# WeiDU Mod Package Builder by Argent77
# See: https://github.com/InfinityTools/WeiduModPackager

name: 'WeiDU Mod Package Builder (iemod; lin/mac: amd64; win: x86-legacy; use git release tag name as suffix)'

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call_workflow_amd64:
    strategy:
      matrix:
        type: [iemod, linux, macos]

    permissions:
      contents: write

    uses: InfinityTools/WeiduModPackagerLibrary/.github/workflows/WeiduModPackagerLibrary.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: amd64
      suffix: ${{ github.event.release.tag_name }}

  call_workflow_x86_legacy:
    permissions:
      contents: write

    uses: InfinityTools/WeiduModPackagerLibrary/.github/workflows/WeiduModPackagerLibrary.yml@master
    with:
      type: windows
      architecture: x86-legacy
      suffix: ${{ github.event.release.tag_name }}
      naming: tp2
