name: 'WeiDU Mod Package Builder (iemod; win: amd64; use git release tag name as suffix)'

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call_workflow:
    strategy:
      matrix:
        type: [iemod, windows]

    permissions:
      contents: write

    uses: InfinityTools/WeiduModPackagerLibrary/.github/workflows/WeiduModPackagerLibrary.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: amd64
      suffix: ${{ github.event.release.tag_name }}
